### ISSUE TITLE
[ Week ] 6주차 워크북 미션

### ISSUE THREAD

**Issue by Yeondu428** [DS-UMC-7th/UMC-7th-Yeondu#9]
### 🛠 Mission

객체지향 프로그래밍(OOP)과 SOILD 원칙 이해하기

### 📝 To-do

- [x] 세부화면 레이아웃 구현
- [ ] OPP적용하여 화면 리펙토링 
- [ ] SOLID적용하여 화면 리펙토링

### 🔍 접근 방법

.
